add-director
IgorMinkov/java-filmorate pull request #13
Opened 2023-11-30 19:52 UTC by tolmachev-es

Добавлен функционал добавления режиссера

2023-11-30 19:54 UTC, zumra6a commented
Нужно прислать PR в develop.

2023-11-30 19:56 UTC, closed without merging

2023-11-30 20:06 UTC, zumra6a requested changes

2023-11-30 20:06 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public void deleteDirector(@PathVariable long directorId) {
id не может быть негативным, добавь плз @Positive к параметру и @Validated к классу

2023-11-30 20:06 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +                String sqlQueryInsert = "INSERT INTO film_directors (film_id, director_id) VALUES (?, ?)";
Можно вынести вверх, не нужно создавать переменную заново, когда значение не меняется.

2023-11-30 20:06 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        if (Objects.nonNull(film.getDirectors()) && !film.getDirectors().isEmpty()) {
а `getDirectors` может быть null? Ещё, ` !film.getDirectors().isEmpty())` не нужно, если коллекция пустая итерация и так не выполнится.

2023-11-30 20:06 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +                jdbcTemplate.update(sqlQueryInsert, film.getId(), director.getId());
Используй пожалуйста `jdbcTemplate.batchUpdate`. Доку и примеры можешь погуглить )

2023-11-30 20:06 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        }
Имхо, `else` тут лишний, линейный код легко читать.

2023-11-30 20:06 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        if (rowsUpdated != 1) {
Кажется, лучше проверять наличие директора до запроса, где-то уровнем выше.

2023-11-30 20:06 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        String sqlQuery = "SELECT * FROM directors";
Не вижу правки в схеме.

2023-12-01 07:36 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public void deleteDirector(@PathVariable long directorId) {
Id у пользователя никак на корректность не проверяются. Тут проблема в том что если пользователь кидает create director. там может быть видимо любое значение. т.к. выдается ему в любом случае новый id.

2023-12-01 07:40 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        }
Согласен, но метод должен что то возвращать. Если if оставить только то у нас будет ошибка метода и код не запуститься.

2023-12-01 07:45 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        }
С чего это не запустится? там в теле if есть return, флоу не дойдёт до throw.

> Если if оставить только то у нас будет ошибка метода и код не запуститься.

какая ошибка и почему код не запустится?

2023-12-01 07:47 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public void deleteDirector(@PathVariable long directorId) {
Не понял. Мы заранее знаем, что айди директора не может быть отрицательным, так почему бы не получить это проверку из коробки добавлением аннотаций?

2023-12-01 08:12 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public void deleteDirector(@PathVariable long directorId) {
Ну тут на самом деле двояко. Я сужу по тестам постмана, например. тут мы подаем нового директора с id = 10.(На данный момент нет ни одного директора) 
![image](https://github.com/IgorMinkov/java-filmorate/assets/134523256/5add4cfb-e910-4e4d-baae-66434f27c519)
В тесте для ответа идет проверка следующая
![image](https://github.com/IgorMinkov/java-filmorate/assets/134523256/4ad3113d-8318-47ec-b857-a9daa115b2c4)
т.е. пользователь в моем понимании может написать туда любое число, но оно никак не будет использоваться. К сожалению тестов на случай в котором id имеет отрицательное значение - нет.

2023-12-01 08:14 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        }
Прикладываю скрин, подробнее можно глянуть в телеграмме 
![image](https://github.com/IgorMinkov/java-filmorate/assets/134523256/9aed2061-744f-4b2c-9bdc-9c2f28db1ff8)

2023-12-01 08:15 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        String sqlQuery = "SELECT * FROM directors";
Правку в схеме добавил в 14 реквесте, этот реквест уже закрыт

2023-12-01 08:45 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        if (Objects.nonNull(film.getDirectors()) && !film.getDirectors().isEmpty()) {
Может быть null.
![image](https://github.com/IgorMinkov/java-filmorate/assets/134523256/1bf165d8-f661-4fdb-a18b-9df32f8701dd)
Так же не исключена вероятность, что пользователь передаст пустое множество. В таком случае проверка на null пройдет успешно т.к. имеется объект класса list. Но он будет пустой так что можно избежать запуск таким образом. Вот пример как это работает.
![image](https://github.com/IgorMinkov/java-filmorate/assets/134523256/50cce318-5453-47f8-9d1f-9037649d505b)

2023-12-01 08:53 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +        if (rowsUpdated != 1) {
Можно делать так. Но с точки зрения оптимизации мы увеличиваем количество запросов к БД в 2 раза

2023-12-01 09:13 UTC, tolmachev-es commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorageDao.java
> +                String sqlQueryInsert = "INSERT INTO film_directors (film_id, director_id) VALUES (?, ?)";
Тут руководствовался так же снижением количества запросов к базе. т.к. В случае с проверкой наличия связей, а потом добавления мы получаем следующий прирост (количество сущностей в запросе - количество новых сущностей) + ( количество новых сущностей * 2) против (1 + количество сущностей) если удалить и потом запихнуть снова.