12.2 Add remove endpoint
IgorMinkov/java-filmorate pull request #15
Opened 2023-12-01 18:11 UTC by Khanbikov-Askhat

Были добавлены методы удаления Фильмов и Пользователей

2023-12-03 10:14 UTC, IgorMinkov approved these changes

2023-12-03 10:14 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Отправлен ответ на PUT-запрос /films/{}", filmId);
тут опечатка? Ответ на put-запрос тут ни при чем.

2023-12-03 10:14 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Отправлен ответ на DELETE-запрос /users/{}", userId);
В дополнении к вопросу выше - такой же случай и логирование оформлено иначе)
Укрепляет в мысли, что в deleteFilm выше опечатка.

2023-12-03 13:26 UTC, Khanbikov-Askhat commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Отправлен ответ на PUT-запрос /films/{}", filmId);
Да, была опечатка, внес изменения

2023-12-04 15:49 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "DELETE FROM films " +
Вроде помещается в одну строку.

2023-12-04 15:51 UTC, zumra6a requested changes

2023-12-04 15:51 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQueryDeleteLike = "DELETE FROM likes " +
Разве по каскаду не удаляются? Проверь пожалуйста. 

Ещё, забыла удалить отзывы и лайки к отзывам.

2023-12-05 08:45 UTC, Khanbikov-Askhat commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQueryDeleteLike = "DELETE FROM likes " +
Не все удаляется каскадом. Добавил удаление отзывов и  лайков к ним

2023-12-05 08:49 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQueryDeleteLike = "DELETE FROM likes " +
@IgorMinkov задай этот вопрос на QA плз, я возможно пропущу встречу.

2023-12-05 08:54 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQueryDeleteLike = "DELETE FROM likes " +
QA был вчера.

2023-12-05 23:17 UTC, Khanbikov-Askhat commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQueryDeleteLike = "DELETE FROM likes " +
Я тоже думал, что каскадом должно делититься, но часть тестов просто перестает проходить

2023-12-07 08:39 UTC, zumra6a approved these changes

2023-12-07 17:14 UTC, merged