New feature has been added to display the most popular films by genre…
IgorMinkov/java-filmorate pull request #16
Opened 2023-12-02 18:57 UTC by ksonic

New feature for display the most popular films by genre and year.

2023-12-03 11:20 UTC, IgorMinkov commented
Конфликты разрешил, влил самую актуальную версию develop тебе в ветку - так же не проходит 4 теста.
Скорректируй, пожалуйста код, чтобы тесты проходили.

2023-12-03 20:45 UTC, ksonic commented
Сейчас тесты проходят. В итоге добавила только  строчку  .peek(film -> film.setDirectors(directorStorage.getByFilmId(film.getId()))) в метод getPopular.

2023-12-03 20:50 UTC, IgorMinkov approved these changes

2023-12-04 15:48 UTC, zumra6a requested changes
Сорян, дальше не буду смотреть. Пуллрик содержит опасные изменения, например, удалила отзывы.

Можешь пожалуйста отребейзить, сосквошить коммиты и запушать ещё раз?

2023-12-04 15:48 UTC, zumra6a commented on pom.xml
> -			<plugin>
а почему удалила?

2023-12-04 15:48 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> -package ru.yandex.practicum.filmorate.model;
воу воу, полехче =) 

Почему удалила?

2023-12-05 08:22 UTC, zumra6a approved these changes
Авансом ставлю апрув. Пройдись плз по замечаниям.

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                      @RequestParam(name = "genreId", required = false) Long genreId) {
Что будет в `year` и `genreId ` если параметр не указан? `null` или пустая строка? 
Может их явно задать в `defaultValue`?

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getPopularFilms(@RequestParam(required = false,
Давай тут укажем `@Positive`,  а в `getPopularFilms` удалим проверку на отрицательное число и null.

1. null он не может быть, из-за `defaultValue = "10"`;
2. `<0` пусть проверяет аннотация.

имхо, так код будет чище.

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> -                " GROUP BY f.film_id ORDER BY COUNT(l.user_id), f.film_id DESC LIMIT (?)";
Давай заменим `LIMIT (?) → LIMIT ?`, в placeholder `?` будет примитив (число), а не выражение.

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> -        String sqlQuery = "SELECT f.film_id, f.name, f.description, f.release_date, f.duration," +
Минор, можно заменить `f.film_id, f.name, f.description, f.release_date, f.duration, → f.*`, так при добавление новой колонки будет +1 место где необходимо указать название.

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return jdbcTemplate.query(resultQuery, FilmDbStorage::buildFilm, sqlArgs.toArray()).stream()
Забыли подгрузить лайки. В разных пуллах выдел прямо копипаст такого кода, может вынесем в метод? Хотелось, чтобы был один метод, который инициализирует фильмы.

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    List<Film> getPopular(Long genreId, String year, Integer limit);
Может оставим оба метода? Игнорируй, если в ТЗ написано, что нужно именно заменить.

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public List<Film> getPopular(Long genreId, String year, Integer limit) {
ну вот, в методе не используется `Long genreId, String year` ¯\_(ツ)_/¯

2023-12-05 08:22 UTC, zumra6a commented on src/main/resources/schema.sql
> +    );
Добавь пустую строку плз.

2023-12-05 08:22 UTC, zumra6a commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> -    private static Film buildFilm(ResultSet rs, int rowNum) throws SQLException {
Не понимаю почему перенесли метод выше, но пусть. Просто такой патч сложно ревьюить, он создаёт когнитивную нагрузку и не несёт пользы. Один разработчик перенёс выше, а другой убрал в конец =)

2023-12-06 19:04 UTC, merged