10.0 Sprint 10 First review
IgorMinkov/java-filmorate pull request #5
Opened 2023-10-30 15:57 UTC by IgorMinkov

Refactor: added Film and User Storages
               added InMemory Storages for Films and Users;
feat: likes and friends for FilmService and UserService;
feat: more endpoints for Film and User Controllers;
feat: exceptiondHandler class.
test: more unit tests for Service methods.
test: as before, most tests 10 Sprint are ia Postman collection. All tests checked and passed before pull request.

2023-10-31 06:43 UTC, Frilock requested changes
Доброе утро, оставил ряд комментариев

2023-10-31 06:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorHandler.java
> +        return new ErrorResponse(
В 1 строку влезает

2023-10-31 06:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorHandler.java
> +        return new ErrorResponse(
Аналогично

2023-10-31 06:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorHandler.java
> +        log.warn(e.getMessage());
Думаю что лучше что то добавить, например, Произошла ошибка: + e.getMessage

2023-10-31 06:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/DataNotFoundException.java
> +public class DataNotFoundException  extends RuntimeException {
Лишний пробел

2023-10-31 06:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void validateFilm(Film film) {
а точно публичный? Где то вне класса используется?

2023-10-31 06:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void validateUser(User user) {
Метод не соотвествует названию, вы не только валидируете имя, но еще и проставляете его. 
Кроме того, метод публичный, он еще где то используется кроме данного класса?
Кроме того, лучше использовать проверку StringUtils.isBlank, которая обьединяет обе проверки в одну

2023-10-31 06:43 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmServiceTests.java
> +                LocalDate.of(2018,6,6),123, new HashSet<>());
после запятых один пробел

2023-10-31 06:43 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTests.java
> +        userService.validateUser(newUser);
Вижу что валидацию проверяете, но делать метод публичным только для того чтобы проверить его в тесте не верно. Проверяйте валидацию, например, через метод создания

2023-10-31 09:25 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorHandler.java
> +        return new ErrorResponse(
✓

2023-10-31 09:26 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorHandler.java
> +        log.warn(e.getMessage());
✓

2023-10-31 09:32 UTC, IgorMinkov commented on src/test/java/ru/yandex/practicum/filmorate/FilmServiceTests.java
> +                LocalDate.of(2018,6,6),123, new HashSet<>());
✓

2023-10-31 09:41 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void validateUser(User user) {
Спасибо, не заметил с первого раза фишку, что и на null проверяет - Checks if a String is whitespace, empty ("") or null.
✓

2023-10-31 09:43 UTC, IgorMinkov commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTests.java
> +        userService.validateUser(newUser);
✓

2023-10-31 09:50 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void validateFilm(Film film) {
Сделал private. Тестируется теперь в тестах создания.
✓

2023-10-31 13:04 UTC, Frilock requested changes
Еще пара комментариев, посмотрите пожалуйста

2023-10-31 13:04 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorHandler.java
>          log.warn(ex.getMessage());
Ну в других методах то тоже надо было =) А то лог будет не красивый

2023-10-31 13:04 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTests.java
>      private User createUser() {
Так это теперь не тест же, зачем метод нужен?

2023-10-31 13:04 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkUserName(User user) {
Все таки мне не очень нравиться что вы в методе проверки еще проставляете значение, на мой взгляд, лучше было бы вообще от него отказаться и эту логику перенести в метод updateUser

2023-11-01 16:49 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/ErrorHandler.java
>          log.warn(ex.getMessage());
Понял, буду знать)
✓

2023-11-01 16:52 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkUserName(User user) {
Логику перенес в метод создания, там более вероятно, что придет пустое имя.
В метод обновления уже проверенные и записанные в БД пользователи будут приходить.

От метода избавился ✓

2023-11-01 16:56 UTC, IgorMinkov commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTests.java
>      private User createUser() {
Вот ту не совсем понял - как раз участок кода, отвечавший за этот тест удален в проверяемом коммите.
Перепроверил, метод этот удален из тестов ранее, а теперь и в целом изначальная логика метода добавлена в другой метод, метод updateUser перестал существовать.
✓

2023-11-01 16:58 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkUserName(User user) {
Актуальный коммит -  10.4

2023-11-01 20:38 UTC, Frilock approved these changes
Принято

2023-11-02 06:51 UTC, merged