Add database sprint 11 review 1
IgorMinkov/java-filmorate pull request #6
Opened 2023-11-18 11:13 UTC by IgorMinkov

feat: dataBase and ER-diagram
feat: genres and mpaRating in model
feat: DAO classes for working with DB.
feat Controllers for genres and mpaRating
test: add a bit of integreation tests for films and users DbStorage crud.

Согласно ТЗ в полном объеме код снова проверяется набором тестов из коллекции Postman.

2023-11-19 10:08 UTC, Frilock requested changes
Добрый день, в целом довольно все хорошо, пара небольших комментариев и можно принимать

2023-11-19 10:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Нужно исправить:
Лишняя аннотация

2023-11-19 10:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaRatingController.java
> +@Slf4j
Нужно исправить:
Лишняя аннотация

2023-11-19 10:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/DataNotFoundException.java
> +
Нужно исправить:
Лишний пропуск строки

2023-11-19 10:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
Можно лучше:
Я бы предложил инициализировать коллекции сразу тут, чтобы избегать проверок на not null в коде

2023-11-19 10:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private Set<Long> friends = new HashSet<>();
Можно лучше:
Зачем убираете инициализацию? Наоборот правильная идея

2023-11-19 10:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Film buildFilm(ResultSet rs, int rowNum) throws SQLException {
Нужно исправить:
Модификатор приватный пропустили

2023-11-19 10:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorageDAO.java
> +    static Genre buildGenre(ResultSet rs, int rowNum) throws SQLException {
аналошично

2023-11-19 11:01 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorageDAO.java
> +    static Genre buildGenre(ResultSet rs, int rowNum) throws SQLException {
✓ везде, где представлен такой класс сделал private

2023-11-19 11:01 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Film buildFilm(ResultSet rs, int rowNum) throws SQLException {
✓

2023-11-19 11:01 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private Set<Long> friends = new HashSet<>();
✓

2023-11-19 11:01 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
✓

2023-11-19 11:01 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/exception/DataNotFoundException.java
> +
✓

2023-11-19 11:01 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaRatingController.java
> +@Slf4j
✓

2023-11-19 11:02 UTC, IgorMinkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
✓ перепроверил контроллеры на лишнюю аннотацию, только в двух местах встречается, удалил.

2023-11-20 18:30 UTC, Frilock approved these changes
Принято

2023-11-27 17:39 UTC, merged